### ISSUE TITLE
category-0.1.2.0 introduced breaking change.

### ISSUE THREAD

**Issue by phadej** [strake/category.hs#1]
http://hdiff.luite.com/cgit/category/diff?id=0.1.2.0&id2=0.1.1.0 shows that you removed an instance

```diff
diff --git a/Control/Category/Groupoid.hs b/Control/Category/Groupoid.hs
index 93e0671..3a59c7b 100644
--- a/Control/Category/Groupoid.hs
+++ b/Control/Category/Groupoid.hs
@@ -1,9 +1,4 @@
-{-# LANGUAGE GADTs #-}
-
 module Control.Category.Groupoid where
 
 class Category k => Groupoid k where
     invert :: k a b -> k b a
-
-instance Groupoid (:~:) where
-    invert Refl = Refl
```

According to PVP you **MUST** do a major bump, i.e. `category-0.1.2.0` should been `category-0.2.0.0`. Someone might relied on existence of that instance. Please be careful next time. (EDIT: previously I said it **SHOULD**, but PVP actually uses most powerful word)

Btw, could you also add
```
bug-reports:         http://github.com/strake/category.hs/issues
```
or/and
```
source-repository head
  type: git
  location: http://github.com/strake/category.hs.git
```

to your packages, so people would more easily find where to report the issues & get the code to contribute.

Cheers, Oleg

**Comment by strake** [comment]
Sorry, this was indeed careless on my part. I rereleased it as [version 0.2.0.0](https://hackage.haskell.org/package/category-0.1.2.0) and noted the issue and repo URLs in the cabal file.

Cheers!

**Comment by strake** [comment]
P.S. The PVP says it actually **MUST** be a major bump.

**Comment by phadej** [comment]
Thanks!
